/** Generated by scripts/register-attack-motions.mjs from reviewed image_gen cels. */
export interface AttackMotionDef {
  src: string;
  poster: string;
  durationMs: number;
}
export const ATTACK_MOTIONS: Record<string, AttackMotionDef> = {
  "moonember": {
    "src": "/art/fx/attacks/moonember.gif",
    "poster": "/art/fx/attacks/moonember.png",
    "durationMs": 520
  },
  "moonsaddle": {
    "src": "/art/fx/attacks/moonsaddle.gif",
    "poster": "/art/fx/attacks/moonsaddle.png",
    "durationMs": 520
  },
  "thundersaddle": {
    "src": "/art/fx/attacks/thundersaddle.gif",
    "poster": "/art/fx/attacks/thundersaddle.png",
    "durationMs": 520
  },
  "miracore": {
    "src": "/art/fx/attacks/miracore.gif",
    "poster": "/art/fx/attacks/miracore.png",
    "durationMs": 520
  },
  "windfeather": {
    "src": "/art/fx/attacks/windfeather.gif",
    "poster": "/art/fx/attacks/windfeather.png",
    "durationMs": 520
  },
  "blossomwing": {
    "src": "/art/fx/attacks/blossomwing.gif",
    "poster": "/art/fx/attacks/blossomwing.png",
    "durationMs": 520
  },
  "clearblade": {
    "src": "/art/fx/attacks/clearblade.gif",
    "poster": "/art/fx/attacks/clearblade.png",
    "durationMs": 520
  },
  "shellwhite": {
    "src": "/art/fx/attacks/shellwhite.gif",
    "poster": "/art/fx/attacks/shellwhite.png",
    "durationMs": 520
  },
  "chartspike": {
    "src": "/art/fx/attacks/chartspike.gif",
    "poster": "/art/fx/attacks/chartspike.png",
    "durationMs": 520
  },
  "thickdive": {
    "src": "/art/fx/attacks/thickdive.gif",
    "poster": "/art/fx/attacks/thickdive.png",
    "durationMs": 520
  },
  "fluffwing": {
    "src": "/art/fx/attacks/fluffwing.gif",
    "poster": "/art/fx/attacks/fluffwing.png",
    "durationMs": 520
  },
  "dawnwing": {
    "src": "/art/fx/attacks/dawnwing.gif",
    "poster": "/art/fx/attacks/dawnwing.png",
    "durationMs": 520
  },
  "lampcloak": {
    "src": "/art/fx/attacks/lampcloak.gif",
    "poster": "/art/fx/attacks/lampcloak.png",
    "durationMs": 520
  },
  "fireflytail": {
    "src": "/art/fx/attacks/fireflytail.gif",
    "poster": "/art/fx/attacks/fireflytail.png",
    "durationMs": 520
  },
  "lampqueen": {
    "src": "/art/fx/attacks/lampqueen.gif",
    "poster": "/art/fx/attacks/lampqueen.png",
    "durationMs": 520
  },
  "tidefin": {
    "src": "/art/fx/attacks/tidefin.gif",
    "poster": "/art/fx/attacks/tidefin.png",
    "durationMs": 520
  },
  "shadebug": {
    "src": "/art/fx/attacks/shadebug.gif",
    "poster": "/art/fx/attacks/shadebug.png",
    "durationMs": 520
  },
  "moonslash": {
    "src": "/art/fx/attacks/moonslash.gif",
    "poster": "/art/fx/attacks/moonslash.png",
    "durationMs": 520
  },
  "shadecoil": {
    "src": "/art/fx/attacks/shadecoil.gif",
    "poster": "/art/fx/attacks/shadecoil.png",
    "durationMs": 520
  },
  "moondrake": {
    "src": "/art/fx/attacks/moondrake.gif",
    "poster": "/art/fx/attacks/moondrake.png",
    "durationMs": 520
  },
  "moonfang": {
    "src": "/art/fx/attacks/moonfang.gif",
    "poster": "/art/fx/attacks/moonfang.png",
    "durationMs": 520
  },
  "windrush": {
    "src": "/art/fx/attacks/windrush.gif",
    "poster": "/art/fx/attacks/windrush.png",
    "durationMs": 520
  },
  "windking": {
    "src": "/art/fx/attacks/windking.gif",
    "poster": "/art/fx/attacks/windking.png",
    "durationMs": 520
  },
  "shellguard": {
    "src": "/art/fx/attacks/shellguard.gif",
    "poster": "/art/fx/attacks/shellguard.png",
    "durationMs": 520
  },
  "shellkeep": {
    "src": "/art/fx/attacks/shellkeep.gif",
    "poster": "/art/fx/attacks/shellkeep.png",
    "durationMs": 520
  },
  "fluffsail": {
    "src": "/art/fx/attacks/fluffsail.gif",
    "poster": "/art/fx/attacks/fluffsail.png",
    "durationMs": 520
  },
  "fluffsky": {
    "src": "/art/fx/attacks/fluffsky.gif",
    "poster": "/art/fx/attacks/fluffsky.png",
    "durationMs": 520
  },
  "fireflymoon": {
    "src": "/art/fx/attacks/fireflymoon.gif",
    "poster": "/art/fx/attacks/fireflymoon.png",
    "durationMs": 520
  },
  "fireflysaint": {
    "src": "/art/fx/attacks/fireflysaint.gif",
    "poster": "/art/fx/attacks/fireflysaint.png",
    "durationMs": 520
  },
  "shadeneedle": {
    "src": "/art/fx/attacks/shadeneedle.gif",
    "poster": "/art/fx/attacks/shadeneedle.png",
    "durationMs": 520
  },
  "shadeend": {
    "src": "/art/fx/attacks/shadeend.gif",
    "poster": "/art/fx/attacks/shadeend.png",
    "durationMs": 520
  },
  "ennya": {
    "src": "/art/fx/attacks/ennya.gif",
    "poster": "/art/fx/attacks/ennya.png",
    "durationMs": 520
  },
  "chickflare": {
    "src": "/art/fx/attacks/chickflare.gif",
    "poster": "/art/fx/attacks/chickflare.png",
    "durationMs": 520
  },
  "waxcat": {
    "src": "/art/fx/attacks/waxcat.gif",
    "poster": "/art/fx/attacks/waxcat.png",
    "durationMs": 520
  },
  "gobflame": {
    "src": "/art/fx/attacks/gobflame.gif",
    "poster": "/art/fx/attacks/gobflame.png",
    "durationMs": 520
  },
  "flarecat": {
    "src": "/art/fx/attacks/flarecat.gif",
    "poster": "/art/fx/attacks/flarecat.png",
    "durationMs": 520
  },
  "ashflare": {
    "src": "/art/fx/attacks/ashflare.gif",
    "poster": "/art/fx/attacks/ashflare.png",
    "durationMs": 520
  },
  "flamewing": {
    "src": "/art/fx/attacks/flamewing.gif",
    "poster": "/art/fx/attacks/flamewing.png",
    "durationMs": 520
  },
  "ashfist": {
    "src": "/art/fx/attacks/ashfist.gif",
    "poster": "/art/fx/attacks/ashfist.png",
    "durationMs": 520
  },
  "tyrantail": {
    "src": "/art/fx/attacks/tyrantail.gif",
    "poster": "/art/fx/attacks/tyrantail.png",
    "durationMs": 520
  },
  "moonflareking": {
    "src": "/art/fx/attacks/moonflareking.gif",
    "poster": "/art/fx/attacks/moonflareking.png",
    "durationMs": 520
  },
  "vermilion": {
    "src": "/art/fx/attacks/vermilion.gif",
    "poster": "/art/fx/attacks/vermilion.png",
    "durationMs": 520
  },
  "emperordrake": {
    "src": "/art/fx/attacks/emperordrake.gif",
    "poster": "/art/fx/attacks/emperordrake.png",
    "durationMs": 520
  },
  "fangpup": {
    "src": "/art/fx/attacks/fangpup.gif",
    "poster": "/art/fx/attacks/fangpup.png",
    "durationMs": 520
  },
  "sesame": {
    "src": "/art/fx/attacks/sesame.gif",
    "poster": "/art/fx/attacks/sesame.png",
    "durationMs": 520
  },
  "penguin": {
    "src": "/art/fx/attacks/penguin.gif",
    "poster": "/art/fx/attacks/penguin.png",
    "durationMs": 520
  },
  "tadpole": {
    "src": "/art/fx/attacks/tadpole.gif",
    "poster": "/art/fx/attacks/tadpole.png",
    "durationMs": 520
  },
  "jellpup": {
    "src": "/art/fx/attacks/jellpup.gif",
    "poster": "/art/fx/attacks/jellpup.png",
    "durationMs": 520
  },
  "frostwolf": {
    "src": "/art/fx/attacks/frostwolf.gif",
    "poster": "/art/fx/attacks/frostwolf.png",
    "durationMs": 520
  },
  "onehorn": {
    "src": "/art/fx/attacks/onehorn.gif",
    "poster": "/art/fx/attacks/onehorn.png",
    "durationMs": 520
  },
  "seadrake": {
    "src": "/art/fx/attacks/seadrake.gif",
    "poster": "/art/fx/attacks/seadrake.png",
    "durationMs": 520
  },
  "snowlump": {
    "src": "/art/fx/attacks/snowlump.gif",
    "poster": "/art/fx/attacks/snowlump.png",
    "durationMs": 520
  },
  "steelfrost": {
    "src": "/art/fx/attacks/steelfrost.gif",
    "poster": "/art/fx/attacks/steelfrost.png",
    "durationMs": 520
  },
  "hammerwhale": {
    "src": "/art/fx/attacks/hammerwhale.gif",
    "poster": "/art/fx/attacks/hammerwhale.png",
    "durationMs": 520
  },
  "tidewhale": {
    "src": "/art/fx/attacks/tidewhale.gif",
    "poster": "/art/fx/attacks/tidewhale.png",
    "durationMs": 520
  },
  "needswing": {
    "src": "/art/fx/attacks/needswing.gif",
    "poster": "/art/fx/attacks/needswing.png",
    "durationMs": 520
  },
  "vinepup": {
    "src": "/art/fx/attacks/vinepup.gif",
    "poster": "/art/fx/attacks/vinepup.png",
    "durationMs": 520
  },
  "sparkkit": {
    "src": "/art/fx/attacks/sparkkit.gif",
    "poster": "/art/fx/attacks/sparkkit.png",
    "durationMs": 520
  },
  "margin": {
    "src": "/art/fx/attacks/margin.gif",
    "poster": "/art/fx/attacks/margin.png",
    "durationMs": 520
  },
  "whipbug": {
    "src": "/art/fx/attacks/whipbug.gif",
    "poster": "/art/fx/attacks/whipbug.png",
    "durationMs": 520
  },
  "shellbolt": {
    "src": "/art/fx/attacks/shellbolt.gif",
    "poster": "/art/fx/attacks/shellbolt.png",
    "durationMs": 520
  },
  "thornball": {
    "src": "/art/fx/attacks/thornball.gif",
    "poster": "/art/fx/attacks/thornball.png",
    "durationMs": 520
  },
  "lampenvoy": {
    "src": "/art/fx/attacks/lampenvoy.gif",
    "poster": "/art/fx/attacks/lampenvoy.png",
    "durationMs": 520
  },
  "beastking": {
    "src": "/art/fx/attacks/beastking.gif",
    "poster": "/art/fx/attacks/beastking.png",
    "durationMs": 520
  },
  "skyfeather": {
    "src": "/art/fx/attacks/skyfeather.gif",
    "poster": "/art/fx/attacks/skyfeather.png",
    "durationMs": 520
  },
  "lampdragon": {
    "src": "/art/fx/attacks/lampdragon.gif",
    "poster": "/art/fx/attacks/lampdragon.png",
    "durationMs": 520
  },
  "thornbloom": {
    "src": "/art/fx/attacks/thornbloom.gif",
    "poster": "/art/fx/attacks/thornbloom.png",
    "durationMs": 520
  },
  "littleshade": {
    "src": "/art/fx/attacks/littleshade.gif",
    "poster": "/art/fx/attacks/littleshade.png",
    "durationMs": 520
  },
  "shadehand": {
    "src": "/art/fx/attacks/shadehand.gif",
    "poster": "/art/fx/attacks/shadehand.png",
    "durationMs": 520
  },
  "venompup": {
    "src": "/art/fx/attacks/venompup.gif",
    "poster": "/art/fx/attacks/venompup.png",
    "durationMs": 520
  },
  "blacktail": {
    "src": "/art/fx/attacks/blacktail.gif",
    "poster": "/art/fx/attacks/blacktail.png",
    "durationMs": 520
  },
  "minishear": {
    "src": "/art/fx/attacks/minishear.gif",
    "poster": "/art/fx/attacks/minishear.png",
    "durationMs": 520
  },
  "nightsteward": {
    "src": "/art/fx/attacks/nightsteward.gif",
    "poster": "/art/fx/attacks/nightsteward.png",
    "durationMs": 520
  },
  "spiritcat": {
    "src": "/art/fx/attacks/spiritcat.gif",
    "poster": "/art/fx/attacks/spiritcat.png",
    "durationMs": 520
  },
  "ironcat": {
    "src": "/art/fx/attacks/ironcat.gif",
    "poster": "/art/fx/attacks/ironcat.png",
    "durationMs": 520
  },
  "nightblade": {
    "src": "/art/fx/attacks/nightblade.gif",
    "poster": "/art/fx/attacks/nightblade.png",
    "durationMs": 520
  },
  "bloodmarquis": {
    "src": "/art/fx/attacks/bloodmarquis.gif",
    "poster": "/art/fx/attacks/bloodmarquis.png",
    "durationMs": 520
  },
  "venomcrown": {
    "src": "/art/fx/attacks/venomcrown.gif",
    "poster": "/art/fx/attacks/venomcrown.png",
    "durationMs": 520
  },
  "calamycore": {
    "src": "/art/fx/attacks/calamycore.gif",
    "poster": "/art/fx/attacks/calamycore.png",
    "durationMs": 520
  },
  "screwkit": {
    "src": "/art/fx/attacks/screwkit.gif",
    "poster": "/art/fx/attacks/screwkit.png",
    "durationMs": 520
  },
  "gearsmith": {
    "src": "/art/fx/attacks/gearsmith.gif",
    "poster": "/art/fx/attacks/gearsmith.png",
    "durationMs": 520
  },
  "glasscat": {
    "src": "/art/fx/attacks/glasscat.gif",
    "poster": "/art/fx/attacks/glasscat.png",
    "durationMs": 520
  },
  "slimekit": {
    "src": "/art/fx/attacks/slimekit.gif",
    "poster": "/art/fx/attacks/slimekit.png",
    "durationMs": 520
  },
  "filthorb": {
    "src": "/art/fx/attacks/filthorb.gif",
    "poster": "/art/fx/attacks/filthorb.png",
    "durationMs": 520
  },
  "starball": {
    "src": "/art/fx/attacks/starball.gif",
    "poster": "/art/fx/attacks/starball.png",
    "durationMs": 520
  },
  "songape": {
    "src": "/art/fx/attacks/songape.gif",
    "poster": "/art/fx/attacks/songape.png",
    "durationMs": 520
  },
  "stoneward": {
    "src": "/art/fx/attacks/stoneward.gif",
    "poster": "/art/fx/attacks/stoneward.png",
    "durationMs": 520
  },
  "threadless": {
    "src": "/art/fx/attacks/threadless.gif",
    "poster": "/art/fx/attacks/threadless.png",
    "durationMs": 520
  },
  "goldape": {
    "src": "/art/fx/attacks/goldape.gif",
    "poster": "/art/fx/attacks/goldape.png",
    "durationMs": 520
  },
  "superstar": {
    "src": "/art/fx/attacks/superstar.gif",
    "poster": "/art/fx/attacks/superstar.png",
    "durationMs": 520
  },
  "twinpole": {
    "src": "/art/fx/attacks/twinpole.gif",
    "poster": "/art/fx/attacks/twinpole.png",
    "durationMs": 520
  },
  "lastchapter": {
    "src": "/art/fx/attacks/lastchapter.gif",
    "poster": "/art/fx/attacks/lastchapter.png",
    "durationMs": 520
  },
  "foxfire": {
    "src": "/art/fx/attacks/foxfire.gif",
    "poster": "/art/fx/attacks/foxfire.png",
    "durationMs": 520
  },
  "foxblaze": {
    "src": "/art/fx/attacks/foxblaze.gif",
    "poster": "/art/fx/attacks/foxblaze.png",
    "durationMs": 520
  },
  "foxnova": {
    "src": "/art/fx/attacks/foxnova.gif",
    "poster": "/art/fx/attacks/foxnova.png",
    "durationMs": 520
  },
  "redwolf": {
    "src": "/art/fx/attacks/redwolf.gif",
    "poster": "/art/fx/attacks/redwolf.png",
    "durationMs": 520
  },
  "redhowl": {
    "src": "/art/fx/attacks/redhowl.gif",
    "poster": "/art/fx/attacks/redhowl.png",
    "durationMs": 520
  },
  "redalpha": {
    "src": "/art/fx/attacks/redalpha.gif",
    "poster": "/art/fx/attacks/redalpha.png",
    "durationMs": 520
  },
  "snowkit": {
    "src": "/art/fx/attacks/snowkit.gif",
    "poster": "/art/fx/attacks/snowkit.png",
    "durationMs": 520
  },
  "snowfang": {
    "src": "/art/fx/attacks/snowfang.gif",
    "poster": "/art/fx/attacks/snowfang.png",
    "durationMs": 520
  },
  "snowking": {
    "src": "/art/fx/attacks/snowking.gif",
    "poster": "/art/fx/attacks/snowking.png",
    "durationMs": 520
  },
  "ripple": {
    "src": "/art/fx/attacks/ripple.gif",
    "poster": "/art/fx/attacks/ripple.png",
    "durationMs": 520
  },
  "tidehorn": {
    "src": "/art/fx/attacks/tidehorn.gif",
    "poster": "/art/fx/attacks/tidehorn.png",
    "durationMs": 520
  },
  "abyssion": {
    "src": "/art/fx/attacks/abyssion.gif",
    "poster": "/art/fx/attacks/abyssion.png",
    "durationMs": 520
  },
  "leafkit": {
    "src": "/art/fx/attacks/leafkit.gif",
    "poster": "/art/fx/attacks/leafkit.png",
    "durationMs": 520
  },
  "vinecat": {
    "src": "/art/fx/attacks/vinecat.gif",
    "poster": "/art/fx/attacks/vinecat.png",
    "durationMs": 520
  },
  "forestor": {
    "src": "/art/fx/attacks/forestor.gif",
    "poster": "/art/fx/attacks/forestor.png",
    "durationMs": 520
  },
  "mothlit": {
    "src": "/art/fx/attacks/mothlit.gif",
    "poster": "/art/fx/attacks/mothlit.png",
    "durationMs": 520
  },
  "silkwing": {
    "src": "/art/fx/attacks/silkwing.gif",
    "poster": "/art/fx/attacks/silkwing.png",
    "durationMs": 520
  },
  "moonmoth": {
    "src": "/art/fx/attacks/moonmoth.gif",
    "poster": "/art/fx/attacks/moonmoth.png",
    "durationMs": 520
  },
  "duskpup": {
    "src": "/art/fx/attacks/duskpup.gif",
    "poster": "/art/fx/attacks/duskpup.png",
    "durationMs": 520
  },
  "nightfang": {
    "src": "/art/fx/attacks/nightfang.gif",
    "poster": "/art/fx/attacks/nightfang.png",
    "durationMs": 520
  },
  "voidhowl": {
    "src": "/art/fx/attacks/voidhowl.gif",
    "poster": "/art/fx/attacks/voidhowl.png",
    "durationMs": 520
  },
  "batling": {
    "src": "/art/fx/attacks/batling.gif",
    "poster": "/art/fx/attacks/batling.png",
    "durationMs": 520
  },
  "bloodwing": {
    "src": "/art/fx/attacks/bloodwing.gif",
    "poster": "/art/fx/attacks/bloodwing.png",
    "durationMs": 520
  },
  "nosferan": {
    "src": "/art/fx/attacks/nosferan.gif",
    "poster": "/art/fx/attacks/nosferan.png",
    "durationMs": 520
  },
  "clockbit": {
    "src": "/art/fx/attacks/clockbit.gif",
    "poster": "/art/fx/attacks/clockbit.png",
    "durationMs": 520
  },
  "gearcat": {
    "src": "/art/fx/attacks/gearcat.gif",
    "poster": "/art/fx/attacks/gearcat.png",
    "durationMs": 520
  },
  "chronos": {
    "src": "/art/fx/attacks/chronos.gif",
    "poster": "/art/fx/attacks/chronos.png",
    "durationMs": 520
  },
  "puffball": {
    "src": "/art/fx/attacks/puffball.gif",
    "poster": "/art/fx/attacks/puffball.png",
    "durationMs": 520
  },
  "puffking": {
    "src": "/art/fx/attacks/puffking.gif",
    "poster": "/art/fx/attacks/puffking.png",
    "durationMs": 520
  },
  "puffnova": {
    "src": "/art/fx/attacks/puffnova.gif",
    "poster": "/art/fx/attacks/puffnova.png",
    "durationMs": 520
  },
  "tyrantking": {
    "src": "/art/fx/attacks/tyrantking.gif",
    "poster": "/art/fx/attacks/tyrantking.png",
    "durationMs": 520
  },
  "blizzardon": {
    "src": "/art/fx/attacks/blizzardon.gif",
    "poster": "/art/fx/attacks/blizzardon.png",
    "durationMs": 520
  },
  "lionheart": {
    "src": "/art/fx/attacks/lionheart.gif",
    "poster": "/art/fx/attacks/lionheart.png",
    "durationMs": 520
  },
  "gobblaze": {
    "src": "/art/fx/attacks/gobblaze.gif",
    "poster": "/art/fx/attacks/gobblaze.png",
    "durationMs": 520
  },
  "gobinferno": {
    "src": "/art/fx/attacks/gobinferno.gif",
    "poster": "/art/fx/attacks/gobinferno.png",
    "durationMs": 520
  },
  "betajelly": {
    "src": "/art/fx/attacks/betajelly.gif",
    "poster": "/art/fx/attacks/betajelly.png",
    "durationMs": 520
  },
  "betaking": {
    "src": "/art/fx/attacks/betaking.gif",
    "poster": "/art/fx/attacks/betaking.png",
    "durationMs": 520
  },
  "kunewhip": {
    "src": "/art/fx/attacks/kunewhip.gif",
    "poster": "/art/fx/attacks/kunewhip.png",
    "durationMs": 520
  },
  "kunestorm": {
    "src": "/art/fx/attacks/kunestorm.gif",
    "poster": "/art/fx/attacks/kunestorm.png",
    "durationMs": 520
  },
  "bigshear": {
    "src": "/art/fx/attacks/bigshear.gif",
    "poster": "/art/fx/attacks/bigshear.png",
    "durationMs": 520
  },
  "shearking": {
    "src": "/art/fx/attacks/shearking.gif",
    "poster": "/art/fx/attacks/shearking.png",
    "durationMs": 520
  },
  "embercub": {
    "src": "/art/fx/attacks/embercub.gif",
    "poster": "/art/fx/attacks/embercub.png",
    "durationMs": 520
  },
  "blazehound": {
    "src": "/art/fx/attacks/blazehound.gif",
    "poster": "/art/fx/attacks/blazehound.png",
    "durationMs": 520
  },
  "infernox": {
    "src": "/art/fx/attacks/infernox.gif",
    "poster": "/art/fx/attacks/infernox.png",
    "durationMs": 520
  },
  "cinder": {
    "src": "/art/fx/attacks/cinder.gif",
    "poster": "/art/fx/attacks/cinder.png",
    "durationMs": 520
  },
  "magmajaw": {
    "src": "/art/fx/attacks/magmajaw.gif",
    "poster": "/art/fx/attacks/magmajaw.png",
    "durationMs": 520
  },
  "volcanus": {
    "src": "/art/fx/attacks/volcanus.gif",
    "poster": "/art/fx/attacks/volcanus.png",
    "durationMs": 520
  },
  "icicle": {
    "src": "/art/fx/attacks/icicle.gif",
    "poster": "/art/fx/attacks/icicle.png",
    "durationMs": 520
  },
  "frosthorn": {
    "src": "/art/fx/attacks/frosthorn.gif",
    "poster": "/art/fx/attacks/frosthorn.png",
    "durationMs": 520
  },
  "glacier": {
    "src": "/art/fx/attacks/glacier.gif",
    "poster": "/art/fx/attacks/glacier.png",
    "durationMs": 520
  },
  "bubblen": {
    "src": "/art/fx/attacks/bubblen.gif",
    "poster": "/art/fx/attacks/bubblen.png",
    "durationMs": 520
  },
  "foamhorn": {
    "src": "/art/fx/attacks/foamhorn.gif",
    "poster": "/art/fx/attacks/foamhorn.png",
    "durationMs": 520
  },
  "tidelord": {
    "src": "/art/fx/attacks/tidelord.gif",
    "poster": "/art/fx/attacks/tidelord.png",
    "durationMs": 520
  },
  "sprout": {
    "src": "/art/fx/attacks/sprout.gif",
    "poster": "/art/fx/attacks/sprout.png",
    "durationMs": 520
  },
  "thornback": {
    "src": "/art/fx/attacks/thornback.gif",
    "poster": "/art/fx/attacks/thornback.png",
    "durationMs": 520
  },
  "worldtree": {
    "src": "/art/fx/attacks/worldtree.gif",
    "poster": "/art/fx/attacks/worldtree.png",
    "durationMs": 520
  },
  "buzzkit": {
    "src": "/art/fx/attacks/buzzkit.gif",
    "poster": "/art/fx/attacks/buzzkit.png",
    "durationMs": 520
  },
  "hornetcat": {
    "src": "/art/fx/attacks/hornetcat.gif",
    "poster": "/art/fx/attacks/hornetcat.png",
    "durationMs": 520
  },
  "queensting": {
    "src": "/art/fx/attacks/queensting.gif",
    "poster": "/art/fx/attacks/queensting.png",
    "durationMs": 520
  },
  "shadekit": {
    "src": "/art/fx/attacks/shadekit.gif",
    "poster": "/art/fx/attacks/shadekit.png",
    "durationMs": 520
  },
  "grimalkin": {
    "src": "/art/fx/attacks/grimalkin.gif",
    "poster": "/art/fx/attacks/grimalkin.png",
    "durationMs": 520
  },
  "umbraking": {
    "src": "/art/fx/attacks/umbraking.gif",
    "poster": "/art/fx/attacks/umbraking.png",
    "durationMs": 520
  },
  "spook": {
    "src": "/art/fx/attacks/spook.gif",
    "poster": "/art/fx/attacks/spook.png",
    "durationMs": 520
  },
  "wraithcat": {
    "src": "/art/fx/attacks/wraithcat.gif",
    "poster": "/art/fx/attacks/wraithcat.png",
    "durationMs": 520
  },
  "phantasm": {
    "src": "/art/fx/attacks/phantasm.gif",
    "poster": "/art/fx/attacks/phantasm.png",
    "durationMs": 520
  },
  "sparkbit": {
    "src": "/art/fx/attacks/sparkbit.gif",
    "poster": "/art/fx/attacks/sparkbit.png",
    "durationMs": 520
  },
  "voltcore": {
    "src": "/art/fx/attacks/voltcore.gif",
    "poster": "/art/fx/attacks/voltcore.png",
    "durationMs": 520
  },
  "thunderforge": {
    "src": "/art/fx/attacks/thunderforge.gif",
    "poster": "/art/fx/attacks/thunderforge.png",
    "durationMs": 520
  },
  "marble": {
    "src": "/art/fx/attacks/marble.gif",
    "poster": "/art/fx/attacks/marble.png",
    "durationMs": 520
  },
  "orbcat": {
    "src": "/art/fx/attacks/orbcat.gif",
    "poster": "/art/fx/attacks/orbcat.png",
    "durationMs": 520
  },
  "cosmos": {
    "src": "/art/fx/attacks/cosmos.gif",
    "poster": "/art/fx/attacks/cosmos.png",
    "durationMs": 520
  },
  "ashcrown": {
    "src": "/art/fx/attacks/ashcrown.gif",
    "poster": "/art/fx/attacks/ashcrown.png",
    "durationMs": 520
  },
  "rosethorn": {
    "src": "/art/fx/attacks/rosethorn.gif",
    "poster": "/art/fx/attacks/rosethorn.png",
    "durationMs": 520
  },
  "deepkeep": {
    "src": "/art/fx/attacks/deepkeep.gif",
    "poster": "/art/fx/attacks/deepkeep.png",
    "durationMs": 520
  },
  "toykings": {
    "src": "/art/fx/attacks/toykings.gif",
    "poster": "/art/fx/attacks/toykings.png",
    "durationMs": 520
  },
  "lampwing": {
    "src": "/art/fx/attacks/lampwing.gif",
    "poster": "/art/fx/attacks/lampwing.png",
    "durationMs": 520
  },
  "errorfang": {
    "src": "/art/fx/attacks/errorfang.gif",
    "poster": "/art/fx/attacks/errorfang.png",
    "durationMs": 520
  },
  "blankfang": {
    "src": "/art/fx/attacks/blankfang.gif",
    "poster": "/art/fx/attacks/blankfang.png",
    "durationMs": 520
  }
};
